---
- name: setup scylla
  shell: >
    scylla_setup
    --no-raid-setup
    --no-node-exporter
  notify: restart scylla
  when:
    - ansible_virtualization_type is defined
    - ansible_virtualization_type == 'docker'

- name: restart scylla
  service:
    name: scylla-server
    state: restarted
    enabled: yes