---
- name: setup scylla
  shell: >
    scylla_setup
    --no-raid-setup
    --no-node-exporter
  notify: restart scylla

- name: restart scylla
  service:
    name: scylla-server
    state: restarted
    enabled: yes